/* soapDeviceIOBindingProxy.h
   Generated by gSOAP 2.8.98 for samples/onvif/onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapDeviceIOBindingProxy_H
#define soapDeviceIOBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC DeviceIOBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'DeviceIOBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in samples/onvif/onvif.h, if any
        /// Construct a proxy with new managing context
        DeviceIOBindingProxy();
        /// Copy constructor
        DeviceIOBindingProxy(const DeviceIOBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        DeviceIOBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        DeviceIOBindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        DeviceIOBindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        DeviceIOBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        DeviceIOBindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        DeviceIOBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~DeviceIOBindingProxy();
        /// Initializer used by constructors
        virtual void DeviceIOBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual DeviceIOBindingProxy *copy();
        /// Copy assignment
        DeviceIOBindingProxy& operator=(const DeviceIOBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsdd__AppSequenceType *wsdd__AppSequence, struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'GetServiceCapabilities' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetServiceCapabilities(_tmd__GetServiceCapabilities *tmd__GetServiceCapabilities, _tmd__GetServiceCapabilitiesResponse &tmd__GetServiceCapabilitiesResponse) { return this->GetServiceCapabilities(NULL, NULL, tmd__GetServiceCapabilities, tmd__GetServiceCapabilitiesResponse); }
        /// Web service synchronous operation 'GetServiceCapabilities' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetServiceCapabilities(const char *soap_endpoint_url, const char *soap_action, _tmd__GetServiceCapabilities *tmd__GetServiceCapabilities, _tmd__GetServiceCapabilitiesResponse &tmd__GetServiceCapabilitiesResponse) { return this->send_GetServiceCapabilities(soap_endpoint_url, soap_action, tmd__GetServiceCapabilities) || this->recv_GetServiceCapabilities(tmd__GetServiceCapabilitiesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetServiceCapabilities' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetServiceCapabilities(const char *soap_endpoint_url, const char *soap_action, _tmd__GetServiceCapabilities *tmd__GetServiceCapabilities);
        /// Web service asynchronous operation 'recv_GetServiceCapabilities' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetServiceCapabilities(_tmd__GetServiceCapabilitiesResponse &tmd__GetServiceCapabilitiesResponse);
        //
        /// Web service synchronous operation 'GetRelayOutputOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetRelayOutputOptions(_tmd__GetRelayOutputOptions *tmd__GetRelayOutputOptions, _tmd__GetRelayOutputOptionsResponse &tmd__GetRelayOutputOptionsResponse) { return this->GetRelayOutputOptions(NULL, NULL, tmd__GetRelayOutputOptions, tmd__GetRelayOutputOptionsResponse); }
        /// Web service synchronous operation 'GetRelayOutputOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetRelayOutputOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetRelayOutputOptions *tmd__GetRelayOutputOptions, _tmd__GetRelayOutputOptionsResponse &tmd__GetRelayOutputOptionsResponse) { return this->send_GetRelayOutputOptions(soap_endpoint_url, soap_action, tmd__GetRelayOutputOptions) || this->recv_GetRelayOutputOptions(tmd__GetRelayOutputOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetRelayOutputOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetRelayOutputOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetRelayOutputOptions *tmd__GetRelayOutputOptions);
        /// Web service asynchronous operation 'recv_GetRelayOutputOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetRelayOutputOptions(_tmd__GetRelayOutputOptionsResponse &tmd__GetRelayOutputOptionsResponse);
        //
        /// Web service synchronous operation 'GetAudioSources' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioSources(tmd__Get *tmd__GetAudioSources, tmd__GetResponse &tmd__GetAudioSourcesResponse) { return this->GetAudioSources(NULL, NULL, tmd__GetAudioSources, tmd__GetAudioSourcesResponse); }
        /// Web service synchronous operation 'GetAudioSources' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioSources(const char *soap_endpoint_url, const char *soap_action, tmd__Get *tmd__GetAudioSources, tmd__GetResponse &tmd__GetAudioSourcesResponse) { return this->send_GetAudioSources(soap_endpoint_url, soap_action, tmd__GetAudioSources) || this->recv_GetAudioSources(tmd__GetAudioSourcesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioSources' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioSources(const char *soap_endpoint_url, const char *soap_action, tmd__Get *tmd__GetAudioSources);
        /// Web service asynchronous operation 'recv_GetAudioSources' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioSources(tmd__GetResponse &tmd__GetAudioSourcesResponse);
        //
        /// Web service synchronous operation 'GetAudioOutputs' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioOutputs(tmd__Get *tmd__GetAudioOutputs, tmd__GetResponse &tmd__GetAudioOutputsResponse) { return this->GetAudioOutputs(NULL, NULL, tmd__GetAudioOutputs, tmd__GetAudioOutputsResponse); }
        /// Web service synchronous operation 'GetAudioOutputs' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioOutputs(const char *soap_endpoint_url, const char *soap_action, tmd__Get *tmd__GetAudioOutputs, tmd__GetResponse &tmd__GetAudioOutputsResponse) { return this->send_GetAudioOutputs(soap_endpoint_url, soap_action, tmd__GetAudioOutputs) || this->recv_GetAudioOutputs(tmd__GetAudioOutputsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioOutputs' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioOutputs(const char *soap_endpoint_url, const char *soap_action, tmd__Get *tmd__GetAudioOutputs);
        /// Web service asynchronous operation 'recv_GetAudioOutputs' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioOutputs(tmd__GetResponse &tmd__GetAudioOutputsResponse);
        //
        /// Web service synchronous operation 'GetVideoSources' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSources(tmd__Get *tmd__GetVideoSources, tmd__GetResponse &tmd__GetVideoSourcesResponse) { return this->GetVideoSources(NULL, NULL, tmd__GetVideoSources, tmd__GetVideoSourcesResponse); }
        /// Web service synchronous operation 'GetVideoSources' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSources(const char *soap_endpoint_url, const char *soap_action, tmd__Get *tmd__GetVideoSources, tmd__GetResponse &tmd__GetVideoSourcesResponse) { return this->send_GetVideoSources(soap_endpoint_url, soap_action, tmd__GetVideoSources) || this->recv_GetVideoSources(tmd__GetVideoSourcesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoSources' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoSources(const char *soap_endpoint_url, const char *soap_action, tmd__Get *tmd__GetVideoSources);
        /// Web service asynchronous operation 'recv_GetVideoSources' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoSources(tmd__GetResponse &tmd__GetVideoSourcesResponse);
        //
        /// Web service synchronous operation 'GetVideoOutputs' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoOutputs(_tmd__GetVideoOutputs *tmd__GetVideoOutputs, _tmd__GetVideoOutputsResponse &tmd__GetVideoOutputsResponse) { return this->GetVideoOutputs(NULL, NULL, tmd__GetVideoOutputs, tmd__GetVideoOutputsResponse); }
        /// Web service synchronous operation 'GetVideoOutputs' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoOutputs(const char *soap_endpoint_url, const char *soap_action, _tmd__GetVideoOutputs *tmd__GetVideoOutputs, _tmd__GetVideoOutputsResponse &tmd__GetVideoOutputsResponse) { return this->send_GetVideoOutputs(soap_endpoint_url, soap_action, tmd__GetVideoOutputs) || this->recv_GetVideoOutputs(tmd__GetVideoOutputsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoOutputs' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoOutputs(const char *soap_endpoint_url, const char *soap_action, _tmd__GetVideoOutputs *tmd__GetVideoOutputs);
        /// Web service asynchronous operation 'recv_GetVideoOutputs' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoOutputs(_tmd__GetVideoOutputsResponse &tmd__GetVideoOutputsResponse);
        //
        /// Web service synchronous operation 'GetVideoSourceConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSourceConfiguration(_tmd__GetVideoSourceConfiguration *tmd__GetVideoSourceConfiguration, _tmd__GetVideoSourceConfigurationResponse &tmd__GetVideoSourceConfigurationResponse) { return this->GetVideoSourceConfiguration(NULL, NULL, tmd__GetVideoSourceConfiguration, tmd__GetVideoSourceConfigurationResponse); }
        /// Web service synchronous operation 'GetVideoSourceConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__GetVideoSourceConfiguration *tmd__GetVideoSourceConfiguration, _tmd__GetVideoSourceConfigurationResponse &tmd__GetVideoSourceConfigurationResponse) { return this->send_GetVideoSourceConfiguration(soap_endpoint_url, soap_action, tmd__GetVideoSourceConfiguration) || this->recv_GetVideoSourceConfiguration(tmd__GetVideoSourceConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoSourceConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__GetVideoSourceConfiguration *tmd__GetVideoSourceConfiguration);
        /// Web service asynchronous operation 'recv_GetVideoSourceConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoSourceConfiguration(_tmd__GetVideoSourceConfigurationResponse &tmd__GetVideoSourceConfigurationResponse);
        //
        /// Web service synchronous operation 'GetVideoOutputConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoOutputConfiguration(_tmd__GetVideoOutputConfiguration *tmd__GetVideoOutputConfiguration, _tmd__GetVideoOutputConfigurationResponse &tmd__GetVideoOutputConfigurationResponse) { return this->GetVideoOutputConfiguration(NULL, NULL, tmd__GetVideoOutputConfiguration, tmd__GetVideoOutputConfigurationResponse); }
        /// Web service synchronous operation 'GetVideoOutputConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoOutputConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__GetVideoOutputConfiguration *tmd__GetVideoOutputConfiguration, _tmd__GetVideoOutputConfigurationResponse &tmd__GetVideoOutputConfigurationResponse) { return this->send_GetVideoOutputConfiguration(soap_endpoint_url, soap_action, tmd__GetVideoOutputConfiguration) || this->recv_GetVideoOutputConfiguration(tmd__GetVideoOutputConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoOutputConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoOutputConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__GetVideoOutputConfiguration *tmd__GetVideoOutputConfiguration);
        /// Web service asynchronous operation 'recv_GetVideoOutputConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoOutputConfiguration(_tmd__GetVideoOutputConfigurationResponse &tmd__GetVideoOutputConfigurationResponse);
        //
        /// Web service synchronous operation 'GetAudioSourceConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioSourceConfiguration(_tmd__GetAudioSourceConfiguration *tmd__GetAudioSourceConfiguration, _tmd__GetAudioSourceConfigurationResponse &tmd__GetAudioSourceConfigurationResponse) { return this->GetAudioSourceConfiguration(NULL, NULL, tmd__GetAudioSourceConfiguration, tmd__GetAudioSourceConfigurationResponse); }
        /// Web service synchronous operation 'GetAudioSourceConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__GetAudioSourceConfiguration *tmd__GetAudioSourceConfiguration, _tmd__GetAudioSourceConfigurationResponse &tmd__GetAudioSourceConfigurationResponse) { return this->send_GetAudioSourceConfiguration(soap_endpoint_url, soap_action, tmd__GetAudioSourceConfiguration) || this->recv_GetAudioSourceConfiguration(tmd__GetAudioSourceConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioSourceConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__GetAudioSourceConfiguration *tmd__GetAudioSourceConfiguration);
        /// Web service asynchronous operation 'recv_GetAudioSourceConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioSourceConfiguration(_tmd__GetAudioSourceConfigurationResponse &tmd__GetAudioSourceConfigurationResponse);
        //
        /// Web service synchronous operation 'GetAudioOutputConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioOutputConfiguration(_tmd__GetAudioOutputConfiguration *tmd__GetAudioOutputConfiguration, _tmd__GetAudioOutputConfigurationResponse &tmd__GetAudioOutputConfigurationResponse) { return this->GetAudioOutputConfiguration(NULL, NULL, tmd__GetAudioOutputConfiguration, tmd__GetAudioOutputConfigurationResponse); }
        /// Web service synchronous operation 'GetAudioOutputConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioOutputConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__GetAudioOutputConfiguration *tmd__GetAudioOutputConfiguration, _tmd__GetAudioOutputConfigurationResponse &tmd__GetAudioOutputConfigurationResponse) { return this->send_GetAudioOutputConfiguration(soap_endpoint_url, soap_action, tmd__GetAudioOutputConfiguration) || this->recv_GetAudioOutputConfiguration(tmd__GetAudioOutputConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioOutputConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioOutputConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__GetAudioOutputConfiguration *tmd__GetAudioOutputConfiguration);
        /// Web service asynchronous operation 'recv_GetAudioOutputConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioOutputConfiguration(_tmd__GetAudioOutputConfigurationResponse &tmd__GetAudioOutputConfigurationResponse);
        //
        /// Web service synchronous operation 'SetVideoSourceConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetVideoSourceConfiguration(_tmd__SetVideoSourceConfiguration *tmd__SetVideoSourceConfiguration, _tmd__SetVideoSourceConfigurationResponse &tmd__SetVideoSourceConfigurationResponse) { return this->SetVideoSourceConfiguration(NULL, NULL, tmd__SetVideoSourceConfiguration, tmd__SetVideoSourceConfigurationResponse); }
        /// Web service synchronous operation 'SetVideoSourceConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetVideoSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__SetVideoSourceConfiguration *tmd__SetVideoSourceConfiguration, _tmd__SetVideoSourceConfigurationResponse &tmd__SetVideoSourceConfigurationResponse) { return this->send_SetVideoSourceConfiguration(soap_endpoint_url, soap_action, tmd__SetVideoSourceConfiguration) || this->recv_SetVideoSourceConfiguration(tmd__SetVideoSourceConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetVideoSourceConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetVideoSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__SetVideoSourceConfiguration *tmd__SetVideoSourceConfiguration);
        /// Web service asynchronous operation 'recv_SetVideoSourceConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetVideoSourceConfiguration(_tmd__SetVideoSourceConfigurationResponse &tmd__SetVideoSourceConfigurationResponse);
        //
        /// Web service synchronous operation 'SetVideoOutputConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetVideoOutputConfiguration(_tmd__SetVideoOutputConfiguration *tmd__SetVideoOutputConfiguration, _tmd__SetVideoOutputConfigurationResponse &tmd__SetVideoOutputConfigurationResponse) { return this->SetVideoOutputConfiguration(NULL, NULL, tmd__SetVideoOutputConfiguration, tmd__SetVideoOutputConfigurationResponse); }
        /// Web service synchronous operation 'SetVideoOutputConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetVideoOutputConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__SetVideoOutputConfiguration *tmd__SetVideoOutputConfiguration, _tmd__SetVideoOutputConfigurationResponse &tmd__SetVideoOutputConfigurationResponse) { return this->send_SetVideoOutputConfiguration(soap_endpoint_url, soap_action, tmd__SetVideoOutputConfiguration) || this->recv_SetVideoOutputConfiguration(tmd__SetVideoOutputConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetVideoOutputConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetVideoOutputConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__SetVideoOutputConfiguration *tmd__SetVideoOutputConfiguration);
        /// Web service asynchronous operation 'recv_SetVideoOutputConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetVideoOutputConfiguration(_tmd__SetVideoOutputConfigurationResponse &tmd__SetVideoOutputConfigurationResponse);
        //
        /// Web service synchronous operation 'SetAudioSourceConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioSourceConfiguration(_tmd__SetAudioSourceConfiguration *tmd__SetAudioSourceConfiguration, _tmd__SetAudioSourceConfigurationResponse &tmd__SetAudioSourceConfigurationResponse) { return this->SetAudioSourceConfiguration(NULL, NULL, tmd__SetAudioSourceConfiguration, tmd__SetAudioSourceConfigurationResponse); }
        /// Web service synchronous operation 'SetAudioSourceConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__SetAudioSourceConfiguration *tmd__SetAudioSourceConfiguration, _tmd__SetAudioSourceConfigurationResponse &tmd__SetAudioSourceConfigurationResponse) { return this->send_SetAudioSourceConfiguration(soap_endpoint_url, soap_action, tmd__SetAudioSourceConfiguration) || this->recv_SetAudioSourceConfiguration(tmd__SetAudioSourceConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetAudioSourceConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetAudioSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__SetAudioSourceConfiguration *tmd__SetAudioSourceConfiguration);
        /// Web service asynchronous operation 'recv_SetAudioSourceConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetAudioSourceConfiguration(_tmd__SetAudioSourceConfigurationResponse &tmd__SetAudioSourceConfigurationResponse);
        //
        /// Web service synchronous operation 'SetAudioOutputConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioOutputConfiguration(_tmd__SetAudioOutputConfiguration *tmd__SetAudioOutputConfiguration, _tmd__SetAudioOutputConfigurationResponse &tmd__SetAudioOutputConfigurationResponse) { return this->SetAudioOutputConfiguration(NULL, NULL, tmd__SetAudioOutputConfiguration, tmd__SetAudioOutputConfigurationResponse); }
        /// Web service synchronous operation 'SetAudioOutputConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioOutputConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__SetAudioOutputConfiguration *tmd__SetAudioOutputConfiguration, _tmd__SetAudioOutputConfigurationResponse &tmd__SetAudioOutputConfigurationResponse) { return this->send_SetAudioOutputConfiguration(soap_endpoint_url, soap_action, tmd__SetAudioOutputConfiguration) || this->recv_SetAudioOutputConfiguration(tmd__SetAudioOutputConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetAudioOutputConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetAudioOutputConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__SetAudioOutputConfiguration *tmd__SetAudioOutputConfiguration);
        /// Web service asynchronous operation 'recv_SetAudioOutputConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetAudioOutputConfiguration(_tmd__SetAudioOutputConfigurationResponse &tmd__SetAudioOutputConfigurationResponse);
        //
        /// Web service synchronous operation 'GetVideoSourceConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSourceConfigurationOptions(_tmd__GetVideoSourceConfigurationOptions *tmd__GetVideoSourceConfigurationOptions, _tmd__GetVideoSourceConfigurationOptionsResponse &tmd__GetVideoSourceConfigurationOptionsResponse) { return this->GetVideoSourceConfigurationOptions(NULL, NULL, tmd__GetVideoSourceConfigurationOptions, tmd__GetVideoSourceConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetVideoSourceConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSourceConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetVideoSourceConfigurationOptions *tmd__GetVideoSourceConfigurationOptions, _tmd__GetVideoSourceConfigurationOptionsResponse &tmd__GetVideoSourceConfigurationOptionsResponse) { return this->send_GetVideoSourceConfigurationOptions(soap_endpoint_url, soap_action, tmd__GetVideoSourceConfigurationOptions) || this->recv_GetVideoSourceConfigurationOptions(tmd__GetVideoSourceConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoSourceConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoSourceConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetVideoSourceConfigurationOptions *tmd__GetVideoSourceConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetVideoSourceConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoSourceConfigurationOptions(_tmd__GetVideoSourceConfigurationOptionsResponse &tmd__GetVideoSourceConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'GetVideoOutputConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoOutputConfigurationOptions(_tmd__GetVideoOutputConfigurationOptions *tmd__GetVideoOutputConfigurationOptions, _tmd__GetVideoOutputConfigurationOptionsResponse &tmd__GetVideoOutputConfigurationOptionsResponse) { return this->GetVideoOutputConfigurationOptions(NULL, NULL, tmd__GetVideoOutputConfigurationOptions, tmd__GetVideoOutputConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetVideoOutputConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoOutputConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetVideoOutputConfigurationOptions *tmd__GetVideoOutputConfigurationOptions, _tmd__GetVideoOutputConfigurationOptionsResponse &tmd__GetVideoOutputConfigurationOptionsResponse) { return this->send_GetVideoOutputConfigurationOptions(soap_endpoint_url, soap_action, tmd__GetVideoOutputConfigurationOptions) || this->recv_GetVideoOutputConfigurationOptions(tmd__GetVideoOutputConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoOutputConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoOutputConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetVideoOutputConfigurationOptions *tmd__GetVideoOutputConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetVideoOutputConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoOutputConfigurationOptions(_tmd__GetVideoOutputConfigurationOptionsResponse &tmd__GetVideoOutputConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'GetAudioSourceConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioSourceConfigurationOptions(_tmd__GetAudioSourceConfigurationOptions *tmd__GetAudioSourceConfigurationOptions, _tmd__GetAudioSourceConfigurationOptionsResponse &tmd__GetAudioSourceConfigurationOptionsResponse) { return this->GetAudioSourceConfigurationOptions(NULL, NULL, tmd__GetAudioSourceConfigurationOptions, tmd__GetAudioSourceConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetAudioSourceConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioSourceConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetAudioSourceConfigurationOptions *tmd__GetAudioSourceConfigurationOptions, _tmd__GetAudioSourceConfigurationOptionsResponse &tmd__GetAudioSourceConfigurationOptionsResponse) { return this->send_GetAudioSourceConfigurationOptions(soap_endpoint_url, soap_action, tmd__GetAudioSourceConfigurationOptions) || this->recv_GetAudioSourceConfigurationOptions(tmd__GetAudioSourceConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioSourceConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioSourceConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetAudioSourceConfigurationOptions *tmd__GetAudioSourceConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetAudioSourceConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioSourceConfigurationOptions(_tmd__GetAudioSourceConfigurationOptionsResponse &tmd__GetAudioSourceConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'GetAudioOutputConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioOutputConfigurationOptions(_tmd__GetAudioOutputConfigurationOptions *tmd__GetAudioOutputConfigurationOptions, _tmd__GetAudioOutputConfigurationOptionsResponse &tmd__GetAudioOutputConfigurationOptionsResponse) { return this->GetAudioOutputConfigurationOptions(NULL, NULL, tmd__GetAudioOutputConfigurationOptions, tmd__GetAudioOutputConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetAudioOutputConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioOutputConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetAudioOutputConfigurationOptions *tmd__GetAudioOutputConfigurationOptions, _tmd__GetAudioOutputConfigurationOptionsResponse &tmd__GetAudioOutputConfigurationOptionsResponse) { return this->send_GetAudioOutputConfigurationOptions(soap_endpoint_url, soap_action, tmd__GetAudioOutputConfigurationOptions) || this->recv_GetAudioOutputConfigurationOptions(tmd__GetAudioOutputConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioOutputConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioOutputConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetAudioOutputConfigurationOptions *tmd__GetAudioOutputConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetAudioOutputConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioOutputConfigurationOptions(_tmd__GetAudioOutputConfigurationOptionsResponse &tmd__GetAudioOutputConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'GetRelayOutputs' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetRelayOutputs(_tds__GetRelayOutputs *tds__GetRelayOutputs, _tds__GetRelayOutputsResponse &tds__GetRelayOutputsResponse) { return this->GetRelayOutputs(NULL, NULL, tds__GetRelayOutputs, tds__GetRelayOutputsResponse); }
        /// Web service synchronous operation 'GetRelayOutputs' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetRelayOutputs(const char *soap_endpoint_url, const char *soap_action, _tds__GetRelayOutputs *tds__GetRelayOutputs, _tds__GetRelayOutputsResponse &tds__GetRelayOutputsResponse) { return this->send_GetRelayOutputs(soap_endpoint_url, soap_action, tds__GetRelayOutputs) || this->recv_GetRelayOutputs(tds__GetRelayOutputsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetRelayOutputs' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetRelayOutputs(const char *soap_endpoint_url, const char *soap_action, _tds__GetRelayOutputs *tds__GetRelayOutputs);
        /// Web service asynchronous operation 'recv_GetRelayOutputs' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetRelayOutputs(_tds__GetRelayOutputsResponse &tds__GetRelayOutputsResponse);
        //
        /// Web service synchronous operation 'SetRelayOutputSettings' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetRelayOutputSettings(_tmd__SetRelayOutputSettings *tmd__SetRelayOutputSettings, _tmd__SetRelayOutputSettingsResponse &tmd__SetRelayOutputSettingsResponse) { return this->SetRelayOutputSettings(NULL, NULL, tmd__SetRelayOutputSettings, tmd__SetRelayOutputSettingsResponse); }
        /// Web service synchronous operation 'SetRelayOutputSettings' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetRelayOutputSettings(const char *soap_endpoint_url, const char *soap_action, _tmd__SetRelayOutputSettings *tmd__SetRelayOutputSettings, _tmd__SetRelayOutputSettingsResponse &tmd__SetRelayOutputSettingsResponse) { return this->send_SetRelayOutputSettings(soap_endpoint_url, soap_action, tmd__SetRelayOutputSettings) || this->recv_SetRelayOutputSettings(tmd__SetRelayOutputSettingsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetRelayOutputSettings' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetRelayOutputSettings(const char *soap_endpoint_url, const char *soap_action, _tmd__SetRelayOutputSettings *tmd__SetRelayOutputSettings);
        /// Web service asynchronous operation 'recv_SetRelayOutputSettings' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetRelayOutputSettings(_tmd__SetRelayOutputSettingsResponse &tmd__SetRelayOutputSettingsResponse);
        //
        /// Web service synchronous operation 'SetRelayOutputState' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetRelayOutputState(_tds__SetRelayOutputState *tds__SetRelayOutputState, _tds__SetRelayOutputStateResponse &tds__SetRelayOutputStateResponse) { return this->SetRelayOutputState(NULL, NULL, tds__SetRelayOutputState, tds__SetRelayOutputStateResponse); }
        /// Web service synchronous operation 'SetRelayOutputState' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetRelayOutputState(const char *soap_endpoint_url, const char *soap_action, _tds__SetRelayOutputState *tds__SetRelayOutputState, _tds__SetRelayOutputStateResponse &tds__SetRelayOutputStateResponse) { return this->send_SetRelayOutputState(soap_endpoint_url, soap_action, tds__SetRelayOutputState) || this->recv_SetRelayOutputState(tds__SetRelayOutputStateResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetRelayOutputState' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetRelayOutputState(const char *soap_endpoint_url, const char *soap_action, _tds__SetRelayOutputState *tds__SetRelayOutputState);
        /// Web service asynchronous operation 'recv_SetRelayOutputState' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetRelayOutputState(_tds__SetRelayOutputStateResponse &tds__SetRelayOutputStateResponse);
        //
        /// Web service synchronous operation 'GetDigitalInputs' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetDigitalInputs(_tmd__GetDigitalInputs *tmd__GetDigitalInputs, _tmd__GetDigitalInputsResponse &tmd__GetDigitalInputsResponse) { return this->GetDigitalInputs(NULL, NULL, tmd__GetDigitalInputs, tmd__GetDigitalInputsResponse); }
        /// Web service synchronous operation 'GetDigitalInputs' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetDigitalInputs(const char *soap_endpoint_url, const char *soap_action, _tmd__GetDigitalInputs *tmd__GetDigitalInputs, _tmd__GetDigitalInputsResponse &tmd__GetDigitalInputsResponse) { return this->send_GetDigitalInputs(soap_endpoint_url, soap_action, tmd__GetDigitalInputs) || this->recv_GetDigitalInputs(tmd__GetDigitalInputsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetDigitalInputs' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetDigitalInputs(const char *soap_endpoint_url, const char *soap_action, _tmd__GetDigitalInputs *tmd__GetDigitalInputs);
        /// Web service asynchronous operation 'recv_GetDigitalInputs' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetDigitalInputs(_tmd__GetDigitalInputsResponse &tmd__GetDigitalInputsResponse);
        //
        /// Web service synchronous operation 'GetDigitalInputConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetDigitalInputConfigurationOptions(_tmd__GetDigitalInputConfigurationOptions *tmd__GetDigitalInputConfigurationOptions, _tmd__GetDigitalInputConfigurationOptionsResponse &tmd__GetDigitalInputConfigurationOptionsResponse) { return this->GetDigitalInputConfigurationOptions(NULL, NULL, tmd__GetDigitalInputConfigurationOptions, tmd__GetDigitalInputConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetDigitalInputConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetDigitalInputConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetDigitalInputConfigurationOptions *tmd__GetDigitalInputConfigurationOptions, _tmd__GetDigitalInputConfigurationOptionsResponse &tmd__GetDigitalInputConfigurationOptionsResponse) { return this->send_GetDigitalInputConfigurationOptions(soap_endpoint_url, soap_action, tmd__GetDigitalInputConfigurationOptions) || this->recv_GetDigitalInputConfigurationOptions(tmd__GetDigitalInputConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetDigitalInputConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetDigitalInputConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetDigitalInputConfigurationOptions *tmd__GetDigitalInputConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetDigitalInputConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetDigitalInputConfigurationOptions(_tmd__GetDigitalInputConfigurationOptionsResponse &tmd__GetDigitalInputConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'SetDigitalInputConfigurations' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetDigitalInputConfigurations(_tmd__SetDigitalInputConfigurations *tmd__SetDigitalInputConfigurations, _tmd__SetDigitalInputConfigurationsResponse &tmd__SetDigitalInputConfigurationsResponse) { return this->SetDigitalInputConfigurations(NULL, NULL, tmd__SetDigitalInputConfigurations, tmd__SetDigitalInputConfigurationsResponse); }
        /// Web service synchronous operation 'SetDigitalInputConfigurations' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetDigitalInputConfigurations(const char *soap_endpoint_url, const char *soap_action, _tmd__SetDigitalInputConfigurations *tmd__SetDigitalInputConfigurations, _tmd__SetDigitalInputConfigurationsResponse &tmd__SetDigitalInputConfigurationsResponse) { return this->send_SetDigitalInputConfigurations(soap_endpoint_url, soap_action, tmd__SetDigitalInputConfigurations) || this->recv_SetDigitalInputConfigurations(tmd__SetDigitalInputConfigurationsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetDigitalInputConfigurations' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetDigitalInputConfigurations(const char *soap_endpoint_url, const char *soap_action, _tmd__SetDigitalInputConfigurations *tmd__SetDigitalInputConfigurations);
        /// Web service asynchronous operation 'recv_SetDigitalInputConfigurations' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetDigitalInputConfigurations(_tmd__SetDigitalInputConfigurationsResponse &tmd__SetDigitalInputConfigurationsResponse);
        //
        /// Web service synchronous operation 'GetSerialPorts' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetSerialPorts(_tmd__GetSerialPorts *tmd__GetSerialPorts, _tmd__GetSerialPortsResponse &tmd__GetSerialPortsResponse) { return this->GetSerialPorts(NULL, NULL, tmd__GetSerialPorts, tmd__GetSerialPortsResponse); }
        /// Web service synchronous operation 'GetSerialPorts' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetSerialPorts(const char *soap_endpoint_url, const char *soap_action, _tmd__GetSerialPorts *tmd__GetSerialPorts, _tmd__GetSerialPortsResponse &tmd__GetSerialPortsResponse) { return this->send_GetSerialPorts(soap_endpoint_url, soap_action, tmd__GetSerialPorts) || this->recv_GetSerialPorts(tmd__GetSerialPortsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetSerialPorts' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetSerialPorts(const char *soap_endpoint_url, const char *soap_action, _tmd__GetSerialPorts *tmd__GetSerialPorts);
        /// Web service asynchronous operation 'recv_GetSerialPorts' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetSerialPorts(_tmd__GetSerialPortsResponse &tmd__GetSerialPortsResponse);
        //
        /// Web service synchronous operation 'GetSerialPortConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetSerialPortConfiguration(_tmd__GetSerialPortConfiguration *tmd__GetSerialPortConfiguration, _tmd__GetSerialPortConfigurationResponse &tmd__GetSerialPortConfigurationResponse) { return this->GetSerialPortConfiguration(NULL, NULL, tmd__GetSerialPortConfiguration, tmd__GetSerialPortConfigurationResponse); }
        /// Web service synchronous operation 'GetSerialPortConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetSerialPortConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__GetSerialPortConfiguration *tmd__GetSerialPortConfiguration, _tmd__GetSerialPortConfigurationResponse &tmd__GetSerialPortConfigurationResponse) { return this->send_GetSerialPortConfiguration(soap_endpoint_url, soap_action, tmd__GetSerialPortConfiguration) || this->recv_GetSerialPortConfiguration(tmd__GetSerialPortConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetSerialPortConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetSerialPortConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__GetSerialPortConfiguration *tmd__GetSerialPortConfiguration);
        /// Web service asynchronous operation 'recv_GetSerialPortConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetSerialPortConfiguration(_tmd__GetSerialPortConfigurationResponse &tmd__GetSerialPortConfigurationResponse);
        //
        /// Web service synchronous operation 'SetSerialPortConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetSerialPortConfiguration(_tmd__SetSerialPortConfiguration *tmd__SetSerialPortConfiguration, _tmd__SetSerialPortConfigurationResponse &tmd__SetSerialPortConfigurationResponse) { return this->SetSerialPortConfiguration(NULL, NULL, tmd__SetSerialPortConfiguration, tmd__SetSerialPortConfigurationResponse); }
        /// Web service synchronous operation 'SetSerialPortConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetSerialPortConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__SetSerialPortConfiguration *tmd__SetSerialPortConfiguration, _tmd__SetSerialPortConfigurationResponse &tmd__SetSerialPortConfigurationResponse) { return this->send_SetSerialPortConfiguration(soap_endpoint_url, soap_action, tmd__SetSerialPortConfiguration) || this->recv_SetSerialPortConfiguration(tmd__SetSerialPortConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetSerialPortConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetSerialPortConfiguration(const char *soap_endpoint_url, const char *soap_action, _tmd__SetSerialPortConfiguration *tmd__SetSerialPortConfiguration);
        /// Web service asynchronous operation 'recv_SetSerialPortConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetSerialPortConfiguration(_tmd__SetSerialPortConfigurationResponse &tmd__SetSerialPortConfigurationResponse);
        //
        /// Web service synchronous operation 'GetSerialPortConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetSerialPortConfigurationOptions(_tmd__GetSerialPortConfigurationOptions *tmd__GetSerialPortConfigurationOptions, _tmd__GetSerialPortConfigurationOptionsResponse &tmd__GetSerialPortConfigurationOptionsResponse) { return this->GetSerialPortConfigurationOptions(NULL, NULL, tmd__GetSerialPortConfigurationOptions, tmd__GetSerialPortConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetSerialPortConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetSerialPortConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetSerialPortConfigurationOptions *tmd__GetSerialPortConfigurationOptions, _tmd__GetSerialPortConfigurationOptionsResponse &tmd__GetSerialPortConfigurationOptionsResponse) { return this->send_GetSerialPortConfigurationOptions(soap_endpoint_url, soap_action, tmd__GetSerialPortConfigurationOptions) || this->recv_GetSerialPortConfigurationOptions(tmd__GetSerialPortConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetSerialPortConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetSerialPortConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, _tmd__GetSerialPortConfigurationOptions *tmd__GetSerialPortConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetSerialPortConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetSerialPortConfigurationOptions(_tmd__GetSerialPortConfigurationOptionsResponse &tmd__GetSerialPortConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'SendReceiveSerialCommand' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SendReceiveSerialCommand(_tmd__SendReceiveSerialCommand *tmd__SendReceiveSerialCommand, _tmd__SendReceiveSerialCommandResponse &tmd__SendReceiveSerialCommandResponse) { return this->SendReceiveSerialCommand(NULL, NULL, tmd__SendReceiveSerialCommand, tmd__SendReceiveSerialCommandResponse); }
        /// Web service synchronous operation 'SendReceiveSerialCommand' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SendReceiveSerialCommand(const char *soap_endpoint_url, const char *soap_action, _tmd__SendReceiveSerialCommand *tmd__SendReceiveSerialCommand, _tmd__SendReceiveSerialCommandResponse &tmd__SendReceiveSerialCommandResponse) { return this->send_SendReceiveSerialCommand(soap_endpoint_url, soap_action, tmd__SendReceiveSerialCommand) || this->recv_SendReceiveSerialCommand(tmd__SendReceiveSerialCommandResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SendReceiveSerialCommand' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SendReceiveSerialCommand(const char *soap_endpoint_url, const char *soap_action, _tmd__SendReceiveSerialCommand *tmd__SendReceiveSerialCommand);
        /// Web service asynchronous operation 'recv_SendReceiveSerialCommand' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SendReceiveSerialCommand(_tmd__SendReceiveSerialCommandResponse &tmd__SendReceiveSerialCommandResponse);
    };
#endif
